name: Michelle Lyall
favicon: null
layout_spectrum: 0.18450409430079162
typography_spectrum: 0.36511245300062
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7485916989389807
  lightness: 0.9211830757558346
  saturation: 0.8046886222437024
  rhythmicContrast: 0.3115286473184824
purpose: []
