typography_spectrum: 0.39022
color:
  brandColors:
    - '#3f87a0'
    - '#ffffff'
    - '#7bbece'
    - '#212020'
    - '#0bd9df'
  brandStrength: 0.3125
  lightness: 0.9211830757558346
  saturation: 0.8125
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.87725
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Michelle Lyall
  email: michelle@michellelyall.com
  url: michellelyall.com
name: Michelle Lyall
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Is Your Perspective The Limitation?
description: Coach & Facilitator
purpose: []
