name: Michelle Lyall
favicon: null
layout_spectrum: 0
typography_spectrum: 0.16297
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9ebfea'
    - '#ffffff'
    - '#282635'
    - '#f06d87'
    - '#e3c361'
  brandStrength: 0.6875
  lightness: 0.9211830757558346
  saturation: 0.8046886222437024
  rhythmicContrast: 0.3115286473184824
purpose: []
