name: Michelle Lyall
favicon: null
layout_spectrum: 0.91916
typography_spectrum: 0.16297
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050503'
    - '#b5cadd'
    - '#358adc'
    - '#760d00'
    - '#c54711'
  brandStrength: 0.1875
  lightness: 0.9211830757558346
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
