typography_spectrum: 0.5122114687692374
color:
  brandColors:
    - '#FFFFFF'
    - '#D00010'
    - '#000000'
    - '#3A6A48'
    - '#E15863'
  brandStrength: 0.26014145091176033
  lightness: 0.3179218654986471
  saturation: 0.1127344905398786
  rhythmicContrast: 0.6442284353543073
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.608348406618461
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Michelle Lyall
  email: michelle@michellelyall.com
  url: michellelyall.com
name: Michelle Lyall
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Is Your Perspective The Limitation?
description: Coach & Facilitator
purpose: []
