name: Michelle Lyall
favicon: null
layout_spectrum: 0.49346
typography_spectrum: 0.16297
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6694cd'
    - '#434246'
    - '#dedde4'
    - '#4a6593'
  brandStrength: 0.625
  lightness: 0.9211830757558346
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
